### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by johnmcd88** [alxnbl/onenote-md-exporter#65]
**Describe the bug**
I'm running onenotemdexporter v1.2 on Windows 10 with Office 2016; I have one notebook named "My Notes" with 24 sections opened in OneNote 2016 . When I try to run onenote-md-exporter from the command line I get a stack dump. Here's the command and resulting dump:

E:\Local Kits\OneNote Markdown Exporter>onenotemdexporter.exe -n "My Notes"
Unhandled exception. System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at alxnbl.OneNoteMdExporter.Program.RunOptions(Options opts)
   at alxnbl.OneNoteMdExporter.Program.<>c.<Main>b__1_0(Options options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at alxnbl.OneNoteMdExporter.Program.Main(String[] args)

If I double-click on the onenote-md-exporter to run it in Windows I get something similar - an 'Invalid cast' exception. I have VisualStudio 2019 installed so I downloaded the source, built the debug solution and ran it in debug. Here's what showed up when I ran it:

![image](https://user-images.githubusercontent.com/6562070/171057637-cc73156d-9f13-4ecc-8038-fafa2f9ce363.png)

**To Reproduce**

Unknown

**Expected behavior**
Program to run and allow me to select, open and export a OneNote notebook..

**Logs**
Both log.txt and error.txt are empty.

**Desktop (please complete the following information):**
 - Windows version : Windows 10 64 bits
 - Office Version : Office 2016 64 bits

**Additional context**

**Comment by alxnbl** [comment]
Hey @johnmcd88 , I encountered this issue on a computer on which the office installation was corrupted. I solved the issue by running the office repair utility, reboot, and restart the tool. Cf: https://support.microsoft.com/en-us/office/repair-an-office-application-7821d4b6-7c1d-4205-aa0e-a6b40c5bb88b .

By the way I will update the code in the next version to display a recommandation of doing this repair when a exception occurs during startup.

Could you try this solution and give me a feedback ?

**Comment by gamexy** [comment]
same problem for me. But I don't have Office, so  the office repair utility can do nothing.

**Comment by alxnbl** [comment]
@gamexy If you don't have office at all, the tool can not work
