### ISSUE TITLE
ErrorPreventToCommunicateWithOneNote

### ISSUE THREAD

**Issue by jimbobshazham** [alxnbl/onenote-md-exporter#86]
**Describe the bug**
The program exits with the following

ErrorPreventToCommunicateWithOneNote
Press [Enter] to continue...

The program then spits the following out:

Unhandled exception. System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.RuntimeTypeHandle.AllocateComObject(Void* pClassFactory)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at alxnbl.OneNoteMdExporter.Program.RunOptions(Options opts) in D:\Alex\Code\onenote-md-exporter\src\OneNoteMdExporter\Program.cs:line 66
   at alxnbl.OneNoteMdExporter.Program.<>c.<Main>b__2_0(Options options) in D:\Alex\Code\onenote-md-exporter\src\OneNoteMdExporter\Program.cs:line 54
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at alxnbl.OneNoteMdExporter.Program.Main(String[] args) in D:\Alex\Code\onenote-md-exporter\src\OneNoteMdExporter\Program.cs:line 47

I suspect something has gone wrong when building the latest release as I don't reckonise the path mentioned in that blurb

**Comment by alxnbl** [comment]
Hey @jimbobshazham , this error seams to be raised on computers with a broken office installation. Can you try to launch the office repair tool, or uninstall and reinstall office. Alternatively, you can transfer your notebooks (export/import) on an other computer and run the OneNodeMdExporter on it. Hope it will help.

**Comment by jimbobshazham** [comment]
I've not owned or ever had office on this computer?

**Comment by alxnbl** [comment]
An office installation is mandatory to run the tool.

**Comment by jimbobshazham** [comment]
I have since figured it out thanks. I do wonder how many times a "corrupt
office install" is trotted out to cover the fact this tool prints no useful
information.

**Comment by alxnbl** [comment]
During startup, the tool display the requirement and specifically the office requirement. So it expects people has read it and do not run the export without Office. But I agree with you that I could update the error message in a future version.

**Comment by jimbobshazham** [comment]
The text posted in the original message is all I saw when I ran it  Had it
displayed what you are suggesting I wouldn't have posted here? It looks
like it failed from the outset and I'm curious what is was doing on a
totally different drive than it was run on.

**Comment by alxnbl** [comment]
Hmm understood !
I was not expecting your error to occur before the display of the welcome message. About the fle path displayed, it is the path of my build folder. Should have been masked during build process.

**Comment by alxnbl** [comment]
Actually, the recommandation is to run both the tool and OneNote without admin privilege.
